### ISSUE TITLE
NTR: Request for S06 Sensible heat flux (BODCNVS-339)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#25] opened 2021-02-12 11:09 UTC
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Sensible heat flux <p><b>Definition</b><p> The transfer of heat caused by the difference in temperature between the sea and the air.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.sciencedirect.com/topics/earth-and-planetary-sciences/sensible-heat-flux<p> <b>ORCID</b><p> 49520162<p>

**Comment by roy-lowry** [comment] 2021-02-12 13:58
The quantity of heat transferred from water to air per unit area per unit time caused by the difference in temperature between the sea and the air.

**Comment by gwemon** [comment] 2021-03-13 11:59
S0600267 queued for publication on the NVS.

**Comment by gwemon** [comment] 2021-03-16 16:38
URI http://vocab.nerc.ac.uk/collection/S06/current/S0600267/ is live

**Closed as completed by gwemon** 2021-03-16 16:38 UTC
